name: rebase
on: [push]

env:
  UPSTREAM_GIT: https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git
  BASE_BRANCH: master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - 
      name: checkout
      uses: actions/checkout@v2
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        fetch-depth: 0
    - 
      name: fetch upstream
      run: |
        git remote add upstream ${UPSTREAM_GIT}
        git fetch upstream
    - 
      name: rebase
      run: |
        git pull --rebase upstream ${BASE_BRANCH}
        git push --force-with-lease
    - 
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DISPATCH }}
        repository: manjaro-sway/manjaro-sway
        event-type: iso_profile_update