on: [push]

env:
  BASE_GIT_HTTPS: https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git
  BASE_BRANCH: master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - 
      name: checkout
      uses: actions/checkout@v2
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
    - 
      name: check if behind base
      run: |
        git remote add base ${BASE_GIT_HTTPS}
        git fetch base
        git merge-base --is-ancestor sway base/${BASE_BRANCH} && exit 1 || exit 0
    - 
      name: rebase
      if: ${{ failure() }}
      run: |
        git rebase base/${BASE_BRANCH}
        git push --force-with-lease
    - 
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        repository: manjaro-sway/manjaro-sway
        event-type: iso_profile_update